# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(941, 441)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        Dialog.setFont(font)
        self.txttienganh = QtWidgets.QTextEdit(Dialog)
        self.txttienganh.setGeometry(QtCore.QRect(50, 90, 351, 251))
        self.txttienganh.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.txttienganh.setFont(font)
        self.txttienganh.setObjectName("txttienganh")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txttiengviet = QtWidgets.QTextEdit(Dialog)
        self.txttiengviet.setGeometry(QtCore.QRect(530, 90, 351, 251))
        self.txttiengviet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.txttiengviet.setFont(font)
        self.txttiengviet.setObjectName("txttiengviet")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(650, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btndich = QtWidgets.QPushButton(Dialog)
        self.btndich.setGeometry(QtCore.QRect(420, 90, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btndich.setFont(font)
        self.btndich.setObjectName("btndich")
        self.btnmicro = QtWidgets.QPushButton(Dialog)
        self.btnmicro.setGeometry(QtCore.QRect(50, 340, 71, 31))
        self.btnmicro.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1082810.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmicro.setIcon(icon)
        self.btnmicro.setObjectName("btnmicro")
        self.btnxoa = QtWidgets.QPushButton(Dialog)
        self.btnxoa.setGeometry(QtCore.QRect(420, 160, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnxoa.setFont(font)
        self.btnxoa.setObjectName("btnxoa")
        self.btnloa2 = QtWidgets.QPushButton(Dialog)
        self.btnloa2.setGeometry(QtCore.QRect(810, 340, 71, 31))
        self.btnloa2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Speaker_Icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnloa2.setIcon(icon1)
        self.btnloa2.setObjectName("btnloa2")
        self.btnloa1 = QtWidgets.QPushButton(Dialog)
        self.btnloa1.setGeometry(QtCore.QRect(120, 340, 71, 31))
        self.btnloa1.setText("")
        self.btnloa1.setIcon(icon1)
        self.btnloa1.setObjectName("btnloa1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tiếng Anh"))
        self.label_2.setText(_translate("Dialog", "Tiếng Việt"))
        self.btndich.setText(_translate("Dialog", "Dịch"))
        self.btnxoa.setText(_translate("Dialog", "Xoá"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
